seo:
  title: Taiyaki Studios
  description: Avatars, production tools, and community resources for next-gen media

discord_invite_link: https://discord.gg/taiyaki

dmca_policy_link: https://storage.googleapis.com/tyk-static/Taiyaki%20-%20Website%20Copyright%20(DMCA)%20Policy%204146-7059-1039%201.pdf
